-- liquibase formatted sql

-- changeset oleksandr_muzyka:1706215402478-1
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid       UUID                                    NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
ALTER TABLE users
    ADD CONSTRAINT uc_users_uuid UNIQUE (uuid);
ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset oleksandr_muzyka:1706215402478-2
CREATE TABLE events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid              UUID                                    NOT NULL,
    name              VARCHAR(255)                            NOT NULL,
    type              VARCHAR(255)                            NOT NULL,
    city              VARCHAR(255)                            NOT NULL,
    city_address      VARCHAR(255)                            NOT NULL,
    description       VARCHAR(300)                            NOT NULL,
    organizer_id      UUID                                    NOT NULL,
    image_name        VARCHAR(255)                            NOT NULL,
    date              TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ticket_price      DECIMAL                                 NOT NULL,
    max_ticket_amount BIGINT                                  NOT NULL,
    is_confirmed      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);
ALTER TABLE events
    ADD CONSTRAINT uc_events_uuid UNIQUE (uuid);
ALTER TABLE events
    ADD CONSTRAINT uc_events_name UNIQUE (name);

